#!/usr/bin/env node

/**
 * Build this worker's two console assets and embed them in the worker:
 *
 *   ui/page.tsx + ui/styles.css → ui/dist/ → src/ui-assets.generated.ts
 *
 * The generated module is why the embed step exists: `deploy: bundle` ships
 * ONE file, so a worker that read `ui/dist` at runtime would serve nothing
 * once published. Rust workers solve this with `include_str!`; a Node worker
 * generates a module and imports it. Invoked as `node ui/build.mjs` from the
 * worker root, hence `root`.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { buildWorkerUi } from '@iii-dev/console-ui/build-worker-ui';

const ui = import.meta.dirname;
const root = join(ui, '..');

async function embed() {
  const [page, styles] = await Promise.all([
    readFile(join(ui, 'dist/page.js'), 'utf8'),
    readFile(join(ui, 'dist/styles.css'), 'utf8'),
  ]);
  const generated = `// Generated by scripts/build-ui.mjs — do not edit.
/* biome-ignore-all lint: generated file */
export const PAGE_JS = ${JSON.stringify(page)};
export const STYLES_CSS = ${JSON.stringify(styles)};
`;
  await mkdir(join(root, 'src'), { recursive: true });
  await writeFile(join(root, 'src/ui-assets.generated.ts'), generated);
}

await buildWorkerUi({
  scope: 'pi',
  root: ui,
  // TODO fase 3: styles.css @imports @iii-workers/agent-terminal-ui's sheet, whose
  // `.agent-terminal*` rules and the @xterm/xterm vendor CSS it pulls in are
  // unscoped. Scope that package's sheet, then drop this.
  allowUnscopedSelectors: ['.xterm', '.agent-terminal'],
  plugins: [
    {
      name: 'embed-after-build',
      setup: (b) => b.onEnd((r) => (r.errors.length ? undefined : embed())),
    },
  ],
});
