#!/usr/bin/env python3
"""Inject the local harness approval-gate rules into generated config.yaml.

The harness config is generated by `iii worker add .` and intentionally not
committed. This script keeps the generated file reproducible by replacing a
small marker-bounded block under the approval-gate worker's `config:` section.
It uses text surgery instead of a YAML dependency because it runs from Makefile
on fresh developer machines.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

START = "# approval-gate-rules:start"
END = "# approval-gate-rules:end"


def indent_block(block: str, indent: str) -> list[str]:
    return [f"{indent}{line}\n" if line else "\n" for line in block.splitlines()]


def strip_managed_block(lines: list[str]) -> list[str]:
    out: list[str] = []
    skipping = False
    for line in lines:
        if START in line:
            skipping = True
            continue
        if END in line:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    if skipping:
        raise SystemExit(f"unterminated managed block: missing {END}")
    return out


def line_indent(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def find_worker_block(lines: list[str]) -> tuple[int, int, int]:
    mapping = re.compile(r"^(\s*)approval-gate:\s*(?:#.*)?$")
    list_item = re.compile(r"^(\s*)-\s+name:\s+approval-gate\s*(?:#.*)?$")

    for idx, line in enumerate(lines):
        match = mapping.match(line) or list_item.match(line)
        if not match:
            continue
        indent = len(match.group(1))
        end = len(lines)
        for j in range(idx + 1, len(lines)):
            stripped = lines[j].strip()
            if not stripped or stripped.startswith("#"):
                continue
            if line_indent(lines[j]) <= indent:
                end = j
                break
        return idx, end, indent

    raise SystemExit("approval-gate worker block not found in generated config")


def inject(config_text: str, rules_text: str) -> str:
    lines = strip_managed_block(config_text.splitlines(keepends=True))
    worker_start, worker_end, worker_indent = find_worker_block(lines)

    config_line = None
    for idx in range(worker_start + 1, worker_end):
        if re.match(r"^\s*config:\s*(?:#.*)?$", lines[idx]):
            config_line = idx
            break

    if config_line is None:
        config_indent = " " * (worker_indent + 2)
        insert_at = worker_start + 1
        lines[insert_at:insert_at] = [f"{config_indent}config:\n"]
        config_line = insert_at
        worker_end += 1

    child_indent = " " * (line_indent(lines[config_line]) + 2)
    managed = [
        f"{child_indent}{START}\n",
        *indent_block(rules_text.strip(), child_indent),
        f"{child_indent}{END}\n",
    ]
    lines[config_line + 1:config_line + 1] = managed
    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, type=Path)
    parser.add_argument("--rules", required=True, type=Path)
    args = parser.parse_args()

    config_text = args.config.read_text()
    rules_text = args.rules.read_text()
    next_text = inject(config_text, rules_text)
    if next_text != config_text:
        args.config.write_text(next_text)


if __name__ == "__main__":
    main()
