export interface UiClasses {
  readonly list: 'iii-ui-list'
  readonly listGroup: 'iii-ui-list-group'
  readonly listGroupLabel: 'iii-ui-list-group__label'
  readonly listItem: 'iii-ui-list-item'
  readonly listItemIcon: 'iii-ui-list-item__icon'
  readonly listItemContent: 'iii-ui-list-item__content'
  readonly listItemTitle: 'iii-ui-list-item__title'
  readonly listItemDescription: 'iii-ui-list-item__description'
  readonly listItemMeta: 'iii-ui-list-item__meta'
  readonly card: 'iii-ui-card'
  readonly cardHeader: 'iii-ui-card__header'
  readonly cardBody: 'iii-ui-card__body'
  readonly panel: 'iii-ui-panel'
  readonly panelHeader: 'iii-ui-panel__header'
  readonly panelBody: 'iii-ui-panel__body'
  readonly chip: 'iii-ui-chip'
  readonly icon: 'iii-ui-icon'
  readonly tableViewport: 'iii-ui-table-viewport'
  readonly tableFrame: 'iii-ui-table-frame'
  readonly table: 'iii-ui-table'
  readonly tableHeader: 'iii-ui-table__header'
  readonly tableBody: 'iii-ui-table__body'
  readonly tableFooter: 'iii-ui-table__footer'
  readonly tableRow: 'iii-ui-table__row'
  readonly tableHead: 'iii-ui-table__head'
  readonly tableCell: 'iii-ui-table__cell'
  readonly tableCaption: 'iii-ui-table__caption'
  readonly tabsList: 'iii-ui-tabs-list'
  readonly tab: 'iii-ui-tab'
  readonly tabIcon: 'iii-ui-tab__icon'
  readonly segmentedControl: 'iii-ui-segmented'
  readonly segmentedItem: 'iii-ui-segmented__item'
  readonly field: 'iii-ui-field'
  readonly fieldLabel: 'iii-ui-field__label'
  readonly fieldDescription: 'iii-ui-field__description'
  readonly fieldError: 'iii-ui-field__error'
  readonly motionControl: 'iii-ui-motion-control'
  readonly motionPanel: 'iii-ui-motion-panel'
  readonly motionOverlay: 'iii-ui-motion-overlay'
}

export declare const uiClasses: UiClasses
export declare const uiClassNames: readonly string[]
export default uiClasses
