/**
 * The Read aloud section: type or paste text and hear it through the
 * configured backend. Every backend returns audio to this browser, with a
 * local Stop control that also ignores a pending synthesis response.
 */

import { Button, Chip, type Host, StatusPanel } from '@iii-dev/console-ui'
import { useState } from 'react'
import { speak } from '../lib/client'
import { SpeakerIcon, StopIcon } from '../lib/icons'
import { useBrowserPlayback } from '../lib/playback'
import type { DoctorResponse } from '../lib/types'
import { Fact, Facts, SectionCard } from './shared'

const SAMPLE = 'Build finished. Three tests failed in the billing module; the rest passed.'

export function ReadAloudSection({ host, report }: { host: Host; report: DoctorResponse }) {
  const [text, setText] = useState(SAMPLE)
  const [selection, setSelection] = useState({ start: 0, end: 0 })
  const selectedText = text.slice(selection.start, selection.end).trim()
  const { state, play, stop } = useBrowserPlayback()
  const { tts } = report
  const disabled = tts.backend === 'off' || !tts.available
  const busy = state.phase === 'speaking' || state.phase === 'loading'
  const onSpeak = () => {
    const body = selectedText || text.trim()
    if (body) void play(() => speak(host.iii, { text: body, text_format: 'markdown' }))
  }

  return (
    <>
      <SectionCard
        title="Read aloud"
        actions={
          <Chip tone={tts.available ? 'success' : 'neutral'}>
            {tts.backend === 'host' ? (tts.command ?? 'host') : tts.backend}
          </Chip>
        }
      >
        <textarea
          className="voice-textarea"
          value={text}
          onChange={(event) => { setText(event.target.value); setSelection({ start: 0, end: 0 }) }}
          onSelect={(event) => setSelection({ start: event.currentTarget.selectionStart, end: event.currentTarget.selectionEnd })}
          rows={4}
          aria-label="text to read aloud"
          placeholder="Type something to hear it…"
        />
        <p className="voice-note">Select a passage above to read only that text, or leave it unselected to read everything.
          {' '}Markdown formatting (bold, italics, headings and links) is not spoken; fenced code blocks are skipped.</p>
        <div className="voice-inline-actions">
          {busy ? (
            <Button variant="primary" onClick={stop}>
              <StopIcon />
              Stop
            </Button>
          ) : (
            <Button
              variant="primary"
              onClick={onSpeak}
              disabled={disabled || !text.trim()}
            >
              <SpeakerIcon />
              {selectedText ? 'Read selection' : 'Speak'}
            </Button>
          )}
          <Button variant="ghost" onClick={() => setText(SAMPLE)} disabled={text === SAMPLE}>
            Reset sample
          </Button>
        </div>
        {state.phase === 'loading' ? <p className="voice-note" role="status">Generating audio for this browser…</p> : null}
        {state.phase === 'error' ? (
          <StatusPanel variant="alert" headline="Could not speak" detail={state.message} />
        ) : null}
        {disabled ? (
          <StatusPanel
            variant="warn"
            headline={tts.backend === 'off' ? 'Read-aloud is off' : 'Read-aloud is not ready'}
            detail={
              tts.problem ?? (tts.backend === 'off'
                ? 'Set tts.backend to host or openai in the voice configuration.'
                : 'Install the selected speech engine on the worker and download its voice in Models.')
            }
          />
        ) : null}
      </SectionCard>
      <SectionCard title="How replies are read">
        <Facts>
          <Fact label="In chat">
            <span className="voice-sub">Each finished turn shows a Read aloud action above the composer.</span>
          </Fact>
          <Fact label="Where it plays">
            <span className="voice-sub">
              Audio is generated by the worker or configured provider and returned only to this browser.
              Nothing plays on the server; Stop affects only this browser.
            </span>
          </Fact>
        </Facts>
      </SectionCard>
    </>
  )
}
