use serde::Deserialize;
use std::path::Path;

/// Narrative-relevant fields from a worker's `iii.worker.yaml`.
///
/// API surface (function ids, signatures, descriptions, custom trigger payloads,
/// config schema) is auto-generated by a different system and is intentionally
/// not represented here.
#[derive(Debug, Deserialize)]
pub struct WorkerManifest {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
}

/// Parse `<dir>/iii.worker.yaml` into the narrative subset.
pub fn read_manifest(_dir: &Path) -> anyhow::Result<WorkerManifest> {
    anyhow::bail!("introspect::read_manifest not yet implemented")
}
