use anyhow::Context;
use serde::Deserialize;
use std::path::Path;

/// Narrative-relevant fields from a worker's `iii.worker.yaml`.
///
/// API surface (function ids, signatures, descriptions, custom trigger payloads,
/// config schema) is auto-generated by a different system and is intentionally
/// not represented here.
#[derive(Debug, Deserialize)]
pub struct WorkerManifest {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
}

/// Parse `<dir>/iii.worker.yaml` into the narrative subset.
pub fn read_manifest(dir: &Path) -> anyhow::Result<WorkerManifest> {
    let path = dir.join("iii.worker.yaml");
    let content = std::fs::read_to_string(&path)
        .with_context(|| format!("reading {}", path.display()))?;
    let manifest: WorkerManifest = serde_yaml::from_str(&content)
        .with_context(|| format!("parsing {}", path.display()))?;
    Ok(manifest)
}
