use anyhow::Context;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Source files that feed into a worker's rendered `README.md`. Listed in the
/// order they appear in the rendered output so the banner reads naturally.
/// Adding a new partial type here updates every worker's README banner on the
/// next render.
const README_SOURCES: &[&str] = &[
    "docs/intro.md",
    "docs/quickstart.md",
    "docs/companions.md",
    "docs/migration.md",
    "iii.worker.yaml",
    "config.yaml",
];

/// Source files that feed into a worker's rendered `skill.md`.
const SKILL_SOURCES: &[&str] = &["docs/intro.md"];

/// Output of rendering one worker.
///
/// `leaves` is keyed by leaf name (e.g. `"analyze"`), value = the full rendered
/// body for `skills/<leaf>.md`. BTreeMap so iteration order is stable.
pub struct RenderOutput {
    pub readme: String,
    pub skill: String,
    pub leaves: BTreeMap<String, String>,
}

/// Render a worker dir into its three artifact strings (no IO writes).
///
/// Reads:
///   - `<dir>/iii.worker.yaml` for `name`
///   - `<dir>/config.yaml` (inlined verbatim into ## Configuration)
///   - `<dir>/docs/intro.md` (used in README and skill.md)
///   - `<dir>/docs/quickstart.md`
///   - `<dir>/docs/companions.md` (optional; appended inside ## Install in README only)
///   - `<dir>/docs/migration.md` (optional)
///   - `<dir>/docs/leaves/*.md` (one per `skills/<leaf>.md` output)
///
/// Does NOT parse `<dir>/src/` — function ids, signatures, descriptions, and
/// custom trigger payloads are auto-generated elsewhere.
pub fn render_worker(dir: &Path) -> anyhow::Result<RenderOutput> {
    let manifest = crate::introspect::read_manifest(dir)?;
    let name = &manifest.name;

    let intro = read_partial(&dir.join("docs").join("intro.md"))?;
    let quickstart = read_partial(&dir.join("docs").join("quickstart.md"))?;
    let config = read_partial(&dir.join("config.yaml"))?;
    let companions = read_optional_partial(&dir.join("docs").join("companions.md"))?;
    let migration = read_optional_partial(&dir.join("docs").join("migration.md"))?;

    let readme = render_readme(
        name,
        &intro,
        &quickstart,
        &config,
        companions.as_deref(),
        migration.as_deref(),
    );
    let skill = render_skill(name, &intro);

    let mut leaves = BTreeMap::new();
    for (leaf_name, leaf_path) in list_leaves(dir)? {
        let body = read_partial(&leaf_path)?;
        let rendered = render_leaf(&leaf_name, &body);
        leaves.insert(leaf_name, rendered);
    }

    Ok(RenderOutput {
        readme,
        skill,
        leaves,
    })
}

fn render_readme(
    name: &str,
    intro: &str,
    quickstart: &str,
    config: &str,
    companions: Option<&str>,
    migration: Option<&str>,
) -> String {
    let mut install_section = format!(
        "## Install\n\n```bash\niii worker add {name}\n```\n\n`iii worker add` fetches the binary, writes a config block into `~/.iii/config.yaml`, and the engine starts the worker on the next `iii start`."
    );
    if let Some(c) = companions {
        install_section.push_str("\n\n");
        install_section.push_str(c);
    }

    let mut sections: Vec<String> = vec![
        banner(README_SOURCES),
        format!("# {name}"),
        intro.to_string(),
        install_section,
        format!("## Quickstart\n\n{quickstart}"),
        format!("## Configuration\n\n```yaml\n{config}\n```"),
    ];
    if let Some(m) = migration {
        sections.push(format!("## Migration notes\n\n{m}"));
    }
    sections.join("\n\n") + "\n"
}

fn render_skill(name: &str, intro: &str) -> String {
    let intro_unwrapped = unwrap_llm_only(intro);
    let sections = vec![
        banner(SKILL_SOURCES),
        format!("# {name}"),
        intro_unwrapped,
    ];
    sections.join("\n\n") + "\n"
}

fn render_leaf(leaf_name: &str, body: &str) -> String {
    let body_unwrapped = unwrap_llm_only(body);
    let leaf_source = format!("docs/leaves/{leaf_name}.md");
    let sections = vec![
        banner(&[leaf_source.as_str()]),
        body_unwrapped,
    ];
    sections.join("\n\n") + "\n"
}

/// Build the "<!-- generated by iii-skill-render — edit X, Y, or Z -->" banner
/// from a list of source files. Format is fixed; the file list comes from the
/// caller so changing the partial set in one place updates every artifact's
/// banner on the next render.
fn banner(sources: &[&str]) -> String {
    format!("<!-- generated by iii-skill-render — edit {} -->", join_or(sources))
}

fn join_or(items: &[&str]) -> String {
    match items.len() {
        0 => String::new(),
        1 => items[0].to_string(),
        _ => {
            let (last, rest) = items.split_last().unwrap();
            format!("{}, or {}", rest.join(", "), last)
        }
    }
}

fn read_partial(path: &Path) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("reading {}", path.display()))?;
    // trim_matches: strip leading + trailing \n. The leading trim handles the
    // common authoring pattern of separating a `<!-- partial-info: ... -->`
    // header from the body with a blank line.
    Ok(strip_partial_info(&content)
        .trim_matches('\n')
        .to_string())
}

fn read_optional_partial(path: &Path) -> anyhow::Result<Option<String>> {
    match std::fs::read_to_string(path) {
        Ok(content) => Ok(Some(
            strip_partial_info(&content).trim_matches('\n').to_string(),
        )),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(anyhow::Error::new(e).context(format!("reading {}", path.display()))),
    }
}

/// Strip partial-info marker lines from a partial. Use at read time so per-file
/// author-pedagogy comments never leak into rendered artifacts. Two forms:
///
///   - HTML: `<!-- partial-info: ... -->` (used in markdown partials).
///   - Hash: `# partial-info: ...` (used in YAML / shell-comment partials such
///     as `config.yaml`, where HTML comments would be invalid syntax).
///
/// Both forms are single-line; multi-line variants are not parsed in v1.
fn strip_partial_info(content: &str) -> String {
    let kept: Vec<&str> = content.lines().filter(|line| !is_partial_info(line)).collect();
    let mut result = kept.join("\n");
    if content.ends_with('\n') {
        result.push('\n');
    }
    result
}

fn is_partial_info(line: &str) -> bool {
    let trimmed = line.trim();
    if trimmed.starts_with("<!-- partial-info:") && trimmed.ends_with("-->") {
        return true;
    }
    if let Some(rest) = trimmed.strip_prefix('#') {
        if rest.trim_start().starts_with("partial-info:") {
            return true;
        }
    }
    false
}

fn list_leaves(dir: &Path) -> anyhow::Result<Vec<(String, PathBuf)>> {
    let leaves_dir = dir.join("docs").join("leaves");
    let mut leaves: Vec<(String, PathBuf)> = Vec::new();
    if !leaves_dir.exists() {
        return Ok(leaves);
    }
    for entry in std::fs::read_dir(&leaves_dir)
        .with_context(|| format!("reading {}", leaves_dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        let name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or_else(|| anyhow::anyhow!("invalid leaf filename: {}", path.display()))?
            .to_string();
        leaves.push((name, path));
    }
    leaves.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(leaves)
}

/// Strip `<!-- llm-only:start -->` / `<!-- llm-only:end -->` block markers and
/// expand `<!-- llm-only: ... -->` inline form to its inner text. Use this when
/// rendering for an LLM-facing target (skill.md, skills/*.md). For a
/// human-facing target (README.md), pass the source through unchanged.
fn unwrap_llm_only(content: &str) -> String {
    let mut out: Vec<String> = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "<!-- llm-only:start -->" || trimmed == "<!-- llm-only:end -->" {
            continue;
        }
        if let Some(inner) = parse_inline_llm_only(trimmed) {
            out.push(inner);
            continue;
        }
        out.push(line.to_string());
    }
    out.join("\n")
}

fn parse_inline_llm_only(trimmed: &str) -> Option<String> {
    let prefix = "<!-- llm-only:";
    let suffix = "-->";
    if !trimmed.starts_with(prefix) || !trimmed.ends_with(suffix) {
        return None;
    }
    if trimmed == "<!-- llm-only:start -->" || trimmed == "<!-- llm-only:end -->" {
        return None;
    }
    let inner = &trimmed[prefix.len()..trimmed.len() - suffix.len()];
    Some(inner.trim().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unwrap_drops_block_markers() {
        let input = "Before\n\n<!-- llm-only:start -->\nInside\n<!-- llm-only:end -->\n\nAfter";
        let expected = "Before\n\nInside\n\nAfter";
        assert_eq!(unwrap_llm_only(input), expected);
    }

    #[test]
    fn unwrap_inline_form_replaces_with_inner() {
        let input = "Before\n<!-- llm-only: short note -->\nAfter";
        let expected = "Before\nshort note\nAfter";
        assert_eq!(unwrap_llm_only(input), expected);
    }

    #[test]
    fn unwrap_idempotent_when_no_markers() {
        let input = "Just plain prose\n\nWith no markers.";
        assert_eq!(unwrap_llm_only(input), input);
    }

    #[test]
    fn unwrap_handles_multiple_blocks() {
        let input = "<!-- llm-only:start -->\nA\n<!-- llm-only:end -->\nmid\n<!-- llm-only:start -->\nB\n<!-- llm-only:end -->";
        let expected = "A\nmid\nB";
        assert_eq!(unwrap_llm_only(input), expected);
    }

    #[test]
    fn strip_partial_info_drops_single_marker() {
        let input = "<!-- partial-info: body shown after the H1 -->\nactual content\n";
        assert_eq!(strip_partial_info(input), "actual content\n");
    }

    #[test]
    fn strip_partial_info_drops_indented_marker() {
        let input = "  <!-- partial-info: leading whitespace tolerated -->\nbody\n";
        assert_eq!(strip_partial_info(input), "body\n");
    }

    #[test]
    fn strip_partial_info_leaves_unrelated_comments_alone() {
        let input = "<!-- llm-only:start -->\nA\n<!-- partial-info: foo -->\nB\n<!-- llm-only:end -->\n";
        let expected = "<!-- llm-only:start -->\nA\nB\n<!-- llm-only:end -->\n";
        assert_eq!(strip_partial_info(input), expected);
    }

    #[test]
    fn strip_partial_info_idempotent_when_no_markers() {
        let input = "plain content\nno markers\n";
        assert_eq!(strip_partial_info(input), input);
    }

    #[test]
    fn strip_partial_info_drops_yaml_hash_form() {
        let input = "# partial-info: worker runtime config\nkey: value\n";
        assert_eq!(strip_partial_info(input), "key: value\n");
    }

    #[test]
    fn strip_partial_info_does_not_drop_unrelated_hash_comments() {
        let input = "# regular YAML comment\nkey: value\n";
        assert_eq!(strip_partial_info(input), input);
    }
}
