import { number, object, objectList, select, text, toggle, variant, variantOption } from '../spec-helpers'
import { choice, type WorkerConfigurationSpec } from '../types'

export const observabilityWorkerSpec = {
  id: 'iii-observability',
  title: 'Observability',
  description: 'OpenTelemetry pipelines, durable trace storage, sampling, metrics, logs, alerts and runtime logging.',
  sections: [
    {
      title: 'Collection and export',
      description: 'Choose how the engine records, samples and exports traces.',
      fields: [
        toggle('enabled', 'Enable observability', 'Collect telemetry and keep the configured pipelines active.', {
          defaultValue: true,
        }),
        select(
          'exporter',
          'Trace exporter',
          [choice('memory', 'Memory'), choice('otlp', 'OTLP'), choice('both', 'Memory and OTLP')],
          undefined,
          { optional: true },
        ),
        number('sampling_ratio', 'Trace sampling ratio', '1 keeps every trace; 0.1 keeps approximately one in ten.', {
          min: 0,
          max: 1,
          step: 0.05,
          optional: true,
        }),
        toggle(
          'live_spans',
          'Show live spans',
          'Mirror in-progress spans into memory. Changing this setting requires an engine restart.',
        ),
        number('memory_max_spans', 'Maximum spans in memory', undefined, { min: 1, step: 1000, optional: true }),
        text('endpoint', 'OTLP endpoint', 'Used by OTLP trace, metric and log exporters.', {
          optional: true,
          placeholder: 'http://localhost:4317',
        }),
      ],
    },
    {
      title: 'Service identity',
      description: 'Resource attributes attached to exported telemetry. Changes apply after an engine restart.',
      fields: [
        text('service_name', 'Service name', undefined, { optional: true, placeholder: 'iii' }),
        text('service_version', 'Service version', 'Environment-variable templates with fallbacks are supported.', {
          optional: true,
        }),
        text('service_namespace', 'Service namespace', undefined, { optional: true }),
      ],
    },
    {
      title: 'Durable trace storage',
      fields: [
        object(
          'trace_storage',
          'Trace storage',
          [
            toggle('enabled', 'Persist completed traces', undefined, { defaultValue: true }),
            text('directory', 'Storage directory', 'Directory containing the SQLite database and WAL files.'),
            number(
              'max_disk_bytes',
              'Maximum disk bytes',
              'Old traces are removed when the directory exceeds this size.',
              {
                min: 67_108_864,
                step: 1_048_576,
              },
            ),
            number('retention_seconds', 'Retention (seconds)', 'Zero disables age-based retention.', { min: 0 }),
            number('memory_max_bytes', 'Hot memory limit (bytes)', undefined, {
              min: 16_777_216,
              step: 1_048_576,
            }),
            number(
              'memory_low_watermark_ratio',
              'Memory low watermark',
              'Cleanup frees memory until usage falls to this fraction of the limit.',
              { min: 0.5, max: 0.95, step: 0.05 },
            ),
            number(
              'pending_max_age_seconds',
              'Pending trace maximum age (seconds)',
              'Closes in-flight snapshots that never receive a final span.',
              { min: 0 },
            ),
          ],
          'Bound hot memory while keeping older completed traces on disk.',
          {
            optional: true,
            defaultValue: {
              enabled: true,
              directory: './data/observability/traces',
              max_disk_bytes: 1_073_741_824,
              retention_seconds: 2_592_000,
              memory_max_bytes: 268_435_456,
              memory_low_watermark_ratio: 0.75,
              pending_max_age_seconds: 3_600,
            },
          },
        ),
      ],
    },
    {
      title: 'Advanced sampling',
      fields: [
        object(
          'sampling',
          'Sampling policy',
          [
            number('default', 'Default sampling ratio', undefined, {
              min: 0,
              max: 1,
              step: 0.05,
              optional: true,
            }),
            toggle('parent_based', 'Honor parent sampling decisions', undefined, { defaultValue: true }),
            object(
              'rate_limit',
              'Rate limit',
              [number('max_traces_per_second', 'Maximum traces per second', undefined, { min: 1 })],
              undefined,
              { optional: true, defaultValue: { max_traces_per_second: 100 } },
            ),
            objectList(
              'rules',
              'Sampling rules',
              'sampling rule',
              { rate: 0.1 },
              [
                text('operation', 'Operation pattern', 'Supports wildcard patterns such as api.*.', { optional: true }),
                text('service', 'Service pattern', undefined, { optional: true }),
                number('rate', 'Sampling ratio', undefined, { min: 0, max: 1, step: 0.05 }),
              ],
              'Rules are evaluated in order before the default sampling ratio.',
              { summaryPaths: [['operation'], ['service']] },
            ),
          ],
          undefined,
          {
            optional: true,
            defaultValue: { default: 1, parent_based: true, rules: [] },
          },
        ),
      ],
    },
    {
      title: 'Metrics',
      fields: [
        toggle('metrics_enabled', 'Enable metrics', undefined, { defaultValue: true }),
        select(
          'metrics_exporter',
          'Metrics exporter',
          [choice('memory', 'Memory'), choice('otlp', 'OTLP')],
          undefined,
          { optional: true },
        ),
        number('metrics_retention_seconds', 'Metrics retention (seconds)', undefined, { min: 1, optional: true }),
        number('metrics_max_count', 'Maximum metric points', undefined, { min: 1, optional: true }),
      ],
    },
    {
      title: 'Logs',
      fields: [
        toggle('logs_enabled', 'Store structured logs', undefined, { defaultValue: true }),
        select(
          'logs_exporter',
          'Logs exporter',
          [choice('memory', 'Memory'), choice('otlp', 'OTLP'), choice('both', 'Memory and OTLP')],
          undefined,
          { optional: true },
        ),
        number('logs_sampling_ratio', 'Logs sampling ratio', undefined, { min: 0, max: 1, step: 0.05 }),
        toggle('logs_console_output', 'Print ingested logs', undefined, { defaultValue: true }),
        number('logs_max_count', 'Maximum logs in memory', undefined, { min: 1, optional: true }),
        number('logs_retention_seconds', 'Logs retention (seconds)', undefined, { min: 1, optional: true }),
        number('logs_batch_size', 'OTLP batch size', undefined, { min: 1, max: 10_000, optional: true }),
        number('logs_flush_interval_ms', 'OTLP flush interval (ms)', undefined, {
          min: 100,
          max: 3_600_000,
          optional: true,
        }),
      ],
    },
    {
      title: 'Runtime logging',
      fields: [
        select(
          'level',
          'Log level',
          [
            choice('trace', 'Trace'),
            choice('debug', 'Debug'),
            choice('info', 'Info'),
            choice('warn', 'Warn'),
            choice('error', 'Error'),
          ],
          'Applies live when set.',
          { optional: true },
        ),
        select(
          'format',
          'Log format',
          [choice('default', 'Human readable'), choice('json', 'JSON')],
          'Changing the log format requires an engine restart.',
          { optional: true },
        ),
      ],
    },
    {
      title: 'Alert rules',
      fields: [
        objectList(
          'alerts',
          'Metric alerts',
          'alert rule',
          {
            name: 'New alert',
            metric: 'iii.invocations.error',
            threshold: 1,
            operator: 'greaterthan',
            window_seconds: 60,
            action: { type: 'log' },
            enabled: true,
            cooldown_seconds: 60,
          },
          [
            text('name', 'Name'),
            text('metric', 'Metric'),
            number('threshold', 'Threshold'),
            select('operator', 'Operator', [
              choice('greaterthan', 'Greater than'),
              choice('greaterthanorequal', 'Greater than or equal'),
              choice('lessthan', 'Less than'),
              choice('lessthanorequal', 'Less than or equal'),
              choice('equal', 'Equal'),
              choice('notequal', 'Not equal'),
            ]),
            number('window_seconds', 'Evaluation window (seconds)', undefined, { min: 1 }),
            number('cooldown_seconds', 'Cooldown (seconds)', undefined, { min: 1 }),
            toggle('enabled', 'Enabled', undefined, { defaultValue: true }),
            variant(
              'action',
              'Action',
              [
                variantOption('log', 'Log', { type: 'log' }, []),
                variantOption('webhook', 'Webhook', { type: 'webhook', url: '' }, [
                  text('url', 'Webhook URL', undefined, { placeholder: 'https://example.com/hooks/alerts' }),
                ]),
                variantOption('function', 'Function', { type: 'function', path: '' }, [text('path', 'Function path')]),
              ],
              'Choose how the alert is delivered.',
              { discriminator: 'type' },
            ),
          ],
          'Alert rules are evaluated against metrics and preserve firing state across live updates.',
          { summaryPaths: [['name'], ['metric']] },
        ),
      ],
    },
    {
      title: 'Trace presentation',
      fields: [
        objectList(
          'collapse_spans',
          'Span collapse rules',
          'collapse rule',
          { name: 'trigger *' },
          [
            text('name', 'Span name pattern'),
            text('service', 'Service pattern', 'Optional service.name pattern.', { optional: true }),
          ],
          'Matching spans are hidden from trace trees and their children are reparented.',
          { summaryPaths: [['name'], ['service']] },
        ),
      ],
    },
  ],
  expectedFields: [
    'enabled',
    'service_name',
    'service_version',
    'service_namespace',
    'exporter',
    'endpoint',
    'sampling_ratio',
    'sampling.default',
    'sampling.rules[].operation',
    'sampling.rules[].service',
    'sampling.rules[].rate',
    'sampling.parent_based',
    'sampling.rate_limit.max_traces_per_second',
    'memory_max_spans',
    'trace_storage.enabled',
    'trace_storage.directory',
    'trace_storage.max_disk_bytes',
    'trace_storage.retention_seconds',
    'trace_storage.memory_max_bytes',
    'trace_storage.memory_low_watermark_ratio',
    'trace_storage.pending_max_age_seconds',
    'live_spans',
    'metrics_enabled',
    'metrics_exporter',
    'metrics_retention_seconds',
    'metrics_max_count',
    'logs_enabled',
    'logs_exporter',
    'logs_max_count',
    'logs_retention_seconds',
    'logs_batch_size',
    'logs_flush_interval_ms',
    'logs_sampling_ratio',
    'logs_console_output',
    'alerts[].name',
    'alerts[].metric',
    'alerts[].threshold',
    'alerts[].operator',
    'alerts[].window_seconds',
    'alerts[].action.type',
    'alerts[].action.url',
    'alerts[].action.path',
    'alerts[].enabled',
    'alerts[].cooldown_seconds',
    'level',
    'format',
    'collapse_spans[].name',
    'collapse_spans[].service',
  ],
} as const satisfies WorkerConfigurationSpec
