//! Tokenization parity with laya's Python `build_sequence`, from committed
//! fixtures (`tests/fixtures/encode.json`, generated by `encode.py` beside it
//! with the real tokenizer, which the tiny fixture shares).
use judge_laya::encode::{render_options, Encoder, QType, Question, Sequence, State};
use serde::Deserialize;
use serde_json::Value;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Case {
    name: String,
    state: Value,
    #[serde(rename = "type")]
    qtype: String,
    instructions: String,
    criteria: Option<Value>,
    options: Vec<String>,
    ids: Vec<u32>,
    markers: Vec<usize>,
    state_dropped: usize,
}

fn fixture() -> (Encoder, Vec<Case>) {
    let fixtures = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let cases: Vec<Case> =
        serde_json::from_slice(&std::fs::read(fixtures.join("encode.json")).unwrap()).unwrap();
    let tokenizer = tokenizers::Tokenizer::from_file(fixtures.join("tiny/tokenizer.json")).unwrap();
    (Encoder::new(tokenizer, 512, 192).unwrap(), cases)
}

fn build(encoder: &Encoder, state: &State, case: &Case) -> Sequence {
    let qtype = match case.qtype.as_str() {
        "choice" => QType::Choice,
        "score" => QType::Score,
        _ => QType::Noul,
    };
    let options = render_options(qtype, case.criteria.as_ref()).unwrap();
    assert_eq!(options, case.options, "{}: rendered options", case.name);
    let question = Question {
        qtype,
        instructions: case.instructions.clone(),
        options,
    };
    encoder.build(state, &question).unwrap()
}

fn assert_matches(sequence: &Sequence, case: &Case) {
    assert_eq!(sequence.markers, case.markers, "{}: markers", case.name);
    assert_eq!(sequence.ids, case.ids, "{}: token ids", case.name);
    assert_eq!(
        sequence.state_dropped, case.state_dropped,
        "{}: dropped state tokens",
        case.name
    );
}

#[test]
fn sequences_match_the_python_reference_token_for_token() {
    let (encoder, cases) = fixture();
    assert!(cases.len() >= 12);
    for case in &cases {
        let state = encoder.state(&case.state).unwrap();
        assert_matches(&build(&encoder, &state, case), case);
    }
}

/// One tokenized state serves every question about it, in any order: each
/// question slices the shared ids to its own room, and the sequences are the
/// ones laya builds tokenizing the state per question.
#[test]
fn a_state_tokenized_once_builds_every_question_like_per_question_tokenization() {
    let (encoder, cases) = fixture();
    let mut shared = 0;
    for (i, first) in cases.iter().enumerate() {
        if cases[..i].iter().any(|seen| seen.state == first.state) {
            continue;
        }
        let state = encoder.state(&first.state).unwrap();
        let questions: Vec<&Case> = cases.iter().filter(|c| c.state == first.state).collect();
        shared += usize::from(questions.len() > 1);
        for case in questions.iter().rev() {
            assert_matches(&build(&encoder, &state, case), case);
        }
    }
    // The ticket and the overflowing conversation each serve several questions.
    assert!(shared >= 2);
}
