//! The language/script detection port against outputs of laya 0.3.28's own
//! `lang.py` (`tests/fixtures/lang.json`, regenerated by `tests/fixtures/lang.py`).
use judge_laya::lang::{analyse, typed_decisions_workflow};
use serde_json::Value;
use std::collections::BTreeMap;

#[test]
fn detection_matches_laya_python_fixtures() {
    let fixtures: BTreeMap<String, Value> =
        serde_json::from_str(include_str!("fixtures/lang.json")).unwrap();
    assert!(fixtures.len() >= 100);
    for (name, case) in fixtures {
        let expected = &case["expected"];
        let got = analyse(&case["input"]);
        assert_eq!(got.script, expected["script"], "{name}: script");
        assert_eq!(
            got.language,
            expected["language"].as_str(),
            "{name}: language"
        );
        assert_eq!(got.is_english, expected["is_english"], "{name}: is_english");
        assert_eq!(
            got.language_undecided, expected["language_undecided"],
            "{name}: language_undecided"
        );
        // Rounded like Python's round(x, 4), so equal to the last bit.
        assert_eq!(
            got.diacritic_rate, expected["diacritic_rate"],
            "{name}: diacritic_rate"
        );
        assert_eq!(
            got.non_latin_fraction, expected["non_latin_fraction"],
            "{name}: non_latin_fraction"
        );
        assert_eq!(
            got.mixed_segment.as_deref(),
            expected["mixed_segment"].as_str(),
            "{name}: mixed_segment"
        );
    }
}

#[test]
fn workflow_signatures_need_the_exact_question_ids() {
    let full = ["urgency", "action", "category", "churn_risk", "needs_human"];
    assert_eq!(
        typed_decisions_workflow(full.into_iter()),
        Some("customer_service")
    );
    assert_eq!(typed_decisions_workflow(full[..4].iter().copied()), None);
    let extra = [
        "urgency",
        "action",
        "category",
        "churn_risk",
        "needs_human",
        "extra",
    ];
    assert_eq!(typed_decisions_workflow(extra.into_iter()), None);
}
